// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbbMNFvfxTjDXOEFgg8NhIPlPMOhwEj-0',
    appId: '1:1055991376090:web:78243562646e2812625de3',
    messagingSenderId: '1055991376090',
    projectId: 'tabz-expense-splitter',
    authDomain: 'tabz-expense-splitter.firebaseapp.com',
    storageBucket: 'tabz-expense-splitter.firebasestorage.app',
    measurementId: 'G-PR24BMNWFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTFhCfvBj9NdpN36aeo1zAKbNw86PIUeY',
    appId: '1:1055991376090:android:e2d93eef69112849625de3',
    messagingSenderId: '1055991376090',
    projectId: 'tabz-expense-splitter',
    storageBucket: 'tabz-expense-splitter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9arOiKRhX0qCjBAmJuzOfEQ0dFLgO5JM',
    appId: '1:1055991376090:ios:7eef84d50d712342625de3',
    messagingSenderId: '1055991376090',
    projectId: 'tabz-expense-splitter',
    storageBucket: 'tabz-expense-splitter.firebasestorage.app',
    androidClientId: '1055991376090-5nun3np3vvtjl1dal3ap7p9logf4v5sl.apps.googleusercontent.com',
    iosClientId: '1055991376090-6is0rm841869ggrfspp36aqvcddtm4c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9arOiKRhX0qCjBAmJuzOfEQ0dFLgO5JM',
    appId: '1:1055991376090:ios:7eef84d50d712342625de3',
    messagingSenderId: '1055991376090',
    projectId: 'tabz-expense-splitter',
    storageBucket: 'tabz-expense-splitter.firebasestorage.app',
    androidClientId: '1055991376090-5nun3np3vvtjl1dal3ap7p9logf4v5sl.apps.googleusercontent.com',
    iosClientId: '1055991376090-6is0rm841869ggrfspp36aqvcddtm4c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbbMNFvfxTjDXOEFgg8NhIPlPMOhwEj-0',
    appId: '1:1055991376090:web:2725a663e8ede7ec625de3',
    messagingSenderId: '1055991376090',
    projectId: 'tabz-expense-splitter',
    authDomain: 'tabz-expense-splitter.firebaseapp.com',
    storageBucket: 'tabz-expense-splitter.firebasestorage.app',
    measurementId: 'G-WML3DQC9YW',
  );

}